=pod

=head1 NAME

Business::CA::GST - Look up Canadian Federal Sales Tax rates

=head1 SYNOPSIS

This is basically a tax table for Canadian GST/HST payments. Please see
L<http://en.wikipedia.org/wiki/Sales_taxes_in_Canada> for a more detailed
explanation of how GST and HST works (it's not as simple as one might hope).

    use Business::CA::GST
    my $tax = Business::CA::GST->new;
    $tax->buyer_region('ON');
    
    print $tax->rate, "\n";     # gives 0.13
    print $tax->tax_type, "\n"; # gives 'HST'

Full documentation for this module can be found in lib/Business/CA/GST.pm

=head2 BUILDING A DISTRIBUTION

To build and test this distro, you'll need to have Dist::Zilla installed.

    dzil test
    dzil build

=head1 AUTHOR

Olaf Alders <olaf@wundercounter.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2010 by Olaf Alders.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
